version: "3"

services:
  primemeridian-website:
    build: .
    container_name: primemeridian-website
    restart: unless-stopped
    ports:
      - 80
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.primemeridian-website.rule=Host(`primemeridian-capital.com`) || Host(`www.primemeridian-capital.com`)"
      - "traefik.http.routers.primemeridian-website.entrypoints=websecure"
      - "traefik.http.routers.primemeridian-website.tls.certResolver=letsencrypt"
      - "traefik.http.services.primemeridian-website.loadbalancer.server.port=80"
      - "traefik.http.routers.primemeridian-website-http.rule=Host(`primemeridian-capital.com`) || Host(`www.primemeridian-capital.com`)"
      - "traefik.http.routers.primemeridian-website-http.entrypoints=web"
      - "traefik.http.routers.primemeridian-website-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  dokploy-network:
    external: true